version: '3.9'

services:
  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    container_name: fastapi_app
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ieum_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - ieum_network

  db:
    image: postgis/postgis:15-3.3
    container_name: postgis_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ieum_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ieum_network

  redis:
    image: redis:7
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ieum_network

networks:
  ieum_network:
    driver: bridge

volumes:
  pgdata:
